// services/ongoingJobs.ts
import apiClient from "../utils/apiClient";

export interface OngoingJob {
  id?: number; // optional because generated by backend
  company_name: string;
  job_title?: string;
  type?: string;
  opportunity?: string; // note spelling as in model, consider fixing to opportunity if backend supports
  Branch?: string;
  package?: number;
  remarks?: string;
  Course?: string;
  min_cgpa?: number;
  deadline?: string; // date as ISO string
  class_12th_percentage?: number;
  class_10th_percentage?: number;
  jobDescriptionLink?:string
  bond?: string;
  stipend?: number;
  handleBy?: string;
  backlog?: string;
  date_updated?: string;
  isApplied?: number; // date as ISO string
}

export const getOngoingJobs = async (): Promise<OngoingJob[]> => {
  const res = await apiClient.get("/ongoing-jobs");
  return res.data;
};

export const getOngoingJobById = async (id: number): Promise<OngoingJob> => {
  const res = await apiClient.get(`/ongoing-jobs/${id}`);
  return res.data;
};

export const createOngoingJob = async (
  data: Partial<OngoingJob>
): Promise<OngoingJob> => {
  const res = await apiClient.post("/ongoing-jobs", data);
  return res.data;
};

export const updateOngoingJob = async (
  id: number,
  data: Partial<OngoingJob>
): Promise<OngoingJob> => {
  const res = await apiClient.put(`/ongoing-jobs/${id}`, data);
  return res.data;
};

export const patchOngoingJob = async (
  id: number,
  data: Partial<OngoingJob>
): Promise<OngoingJob> => {
  const res = await apiClient.patch(`/ongoing-jobs/${id}`, data);
  return res.data;
};

export const deleteOngoingJob = async (id: number): Promise<void> => {
  await apiClient.delete(`/ongoing-jobs/${id}`);
};
